var jscolor={dir:"",bindClass:"color",binding:!0,preloading:!0,install:function(){},init:function(){jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var b=jscolor.detectDir();jscolor.dir=!1!==b?b:window.RESOURCES_PATH}return jscolor.dir},detectDir:function(){for(var b=location.href,e=document.getElementsByTagName("base"),a=0;a<e.length;a+=1)e[a].href&&(b=e[a].href);e=document.getElementsByTagName("script");for(a=0;a<e.length;a+=1)if(e[a].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(e[a].src))return b=
(new jscolor.URI(e[a].src)).toAbsolute(b),b.path=b.path.replace(/[^\/]+$/,""),b.query=null,b.fragment=null,b.toString();return!1},preload:function(){for(var b in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(b)&&jscolor.loadImage(b)},images:{pad:[181,101],sld:[16,101],cross:[15,15],arrow:[7,11]},imgRequire:{},imgLoaded:{},requireImage:function(b){jscolor.imgRequire[b]=!0},loadImage:function(b){jscolor.imgLoaded[b]||(jscolor.imgLoaded[b]=new Image,jscolor.imgLoaded[b].src=jscolor.getDir()+b)},
fetchElement:function(b){return"string"===typeof b?document.getElementById(b):b},addEvent:function(b,e,a){b.addEventListener?b.addEventListener(e,a,!1):b.attachEvent&&b.attachEvent("on"+e,a)},fireEvent:function(b,e){if(b)if(document.createEvent){var a=document.createEvent("HTMLEvents");a.initEvent(e,!0,!0);b.dispatchEvent(a)}else if(document.createEventObject)a=document.createEventObject(),b.fireEvent("on"+e,a);else if(b["on"+e])b["on"+e]()},getElementPos:function(b){var e=b,a=0,m=0;if(e.offsetParent){do a+=
e.offsetLeft,m+=e.offsetTop;while(e=e.offsetParent)}for(;(b=b.parentNode)&&"BODY"!==b.nodeName.toUpperCase();)a-=b.scrollLeft,m-=b.scrollTop;return[a,m]},getElementSize:function(b){return[b.offsetWidth,b.offsetHeight]},getRelMousePos:function(b){var e=0,a=0;b||(b=window.event);"number"===typeof b.offsetX?(e=b.offsetX,a=b.offsetY):"number"===typeof b.layerX&&(e=b.layerX,a=b.layerY);return{x:e,y:a}},getViewPos:function(){return"number"===typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:
document.body&&(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return"number"===typeof window.innerWidth?[window.innerWidth,window.innerHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:
document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:[0,0]},URI:function(b){function e(a){for(var b="";a;)if("../"===a.substr(0,3)||"./"===a.substr(0,2))a=a.replace(/^\.+/,"").substr(1);else if("/./"===a.substr(0,3)||"/."===a)a="/"+a.substr(3);else if("/../"===a.substr(0,4)||"/.."===a)a="/"+a.substr(4),b=b.replace(/\/?[^\/]*$/,"");else if("."===a||".."===a)a="";else{var e=
a.match(/^\/?[^\/]*/)[0];a=a.substr(e.length);b+=e}return b}this.authority=this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(a){a=a.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=a[3]?a[2]:null;this.authority=a[5]?a[6]:null;this.path=a[7];this.query=a[9]?a[10]:null;this.fragment=a[12]?a[13]:null;return this};this.toString=function(){var a="";null!==this.scheme&&(a=a+this.scheme+":");null!==this.authority&&(a=a+
"//"+this.authority);null!==this.path&&(a+=this.path);null!==this.query&&(a=a+"?"+this.query);null!==this.fragment&&(a=a+"#"+this.fragment);return a};this.toAbsolute=function(a){a=new jscolor.URI(a);var b=new jscolor.URI;if(null===a.scheme)return!1;null!==this.scheme&&this.scheme.toLowerCase()===a.scheme.toLowerCase()&&(this.scheme=null);null!==this.scheme?(b.scheme=this.scheme,b.authority=this.authority,b.path=e(this.path),b.query=this.query):(null!==this.authority?(b.authority=this.authority,b.path=
e(this.path),b.query=this.query):(""===this.path?(b.path=a.path,b.query=null!==this.query?this.query:a.query):("/"===this.path.substr(0,1)?b.path=e(this.path):(b.path=null!==a.authority&&""===a.path?"/"+this.path:a.path.replace(/[^\/]+$/,"")+this.path,b.path=e(b.path)),b.query=this.query),b.authority=a.authority),b.scheme=a.scheme);b.fragment=this.fragment;return b};b&&this.parse(b)},color:function(b,e){function a(g,b,a){if(null===g)return[a,a,a];var d=Math.floor(g),c=a*(1-b);g=a*(1-b*(d%2?g-d:1-
(g-d)));switch(d){case 6:case 0:return[a,g,c];case 1:return[g,a,c];case 2:return[c,a,g];case 3:return[c,g,a];case 4:return[g,c,a];case 5:return[a,c,g]}}function m(g,a){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),btn:document.createElement("div"),
btnS:document.createElement("span"),btnT:document.createTextNode(d.pickerCloseText)};for(var k=0;k<jscolor.images.sld[1];k+=4){var e=document.createElement("div");e.style.height="4px";e.style.fontSize="1px";e.style.lineHeight="0";jscolor.picker.sld.appendChild(e)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);
jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);jscolor.picker.boxB.appendChild(jscolor.picker.box)}var c=jscolor.picker;c.box.onmouseup=c.box.onmouseout=function(){mxClient.IS_TOUCH||b.focus()};c.box.onmousedown=function(){};c.box.onmousemove=function(a){if(n||p)n&&z(a),p&&A(a),document.selection?document.selection.empty():window.getSelection&&
window.getSelection().removeAllRanges(),r()};c.padM.onmouseup=c.padM.onmouseout=function(){n&&(n=!1,jscolor.fireEvent(h,"change"))};c.padM.onmousedown=function(a){switch(l){case 0:0===d.hsv[2]&&d.fromHSV(null,null,1);break;case 1:0===d.hsv[1]&&d.fromHSV(null,1,null)}n=!0;z(a);r()};c.sldM.onmouseup=c.sldM.onmouseout=function(){p&&(p=!1,jscolor.fireEvent(h,"change"))};c.sldM.onmousedown=function(a){p=!0;A(a);r()};k=y(d);c.box.style.width=k[0]+"px";c.box.style.height=k[1]+"px";c.boxB.style.position=
"absolute";c.boxB.style.clear="both";c.boxB.style.left=g+"px";c.boxB.style.top=a+"px";c.boxB.style.zIndex=d.pickerZIndex;c.boxB.style.border=d.pickerBorder+"px solid";c.boxB.style.borderColor=d.pickerBorderColor;c.boxB.style.background=d.pickerFaceColor;c.pad.style.width=jscolor.images.pad[0]+"px";c.pad.style.height=jscolor.images.pad[1]+"px";c.padB.style.position="absolute";c.padB.style.left=d.pickerFace+"px";c.padB.style.top=d.pickerFace+"px";c.padB.style.border=d.pickerInset+"px solid";c.padB.style.borderColor=
d.pickerInsetColor;c.padM.style.position="absolute";c.padM.style.left="0";c.padM.style.top="0";c.padM.style.width=d.pickerFace+2*d.pickerInset+jscolor.images.pad[0]+jscolor.images.arrow[0]+"px";c.padM.style.height=c.box.style.height;c.padM.style.cursor="crosshair";c.sld.style.overflow="hidden";c.sld.style.width=jscolor.images.sld[0]+"px";c.sld.style.height=jscolor.images.sld[1]+"px";c.sldB.style.display=d.slider?"block":"none";c.sldB.style.position="absolute";c.sldB.style.right=d.pickerFace+"px";
c.sldB.style.top=d.pickerFace+"px";c.sldB.style.border=d.pickerInset+"px solid";c.sldB.style.borderColor=d.pickerInsetColor;c.sldM.style.display=d.slider?"block":"none";c.sldM.style.position="absolute";c.sldM.style.right="0";c.sldM.style.top="0";c.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+d.pickerFace+2*d.pickerInset+"px";c.sldM.style.height=c.box.style.height;try{c.sldM.style.cursor="pointer"}catch(D){c.sldM.style.cursor="hand"}c.btn.style.display=d.pickerClosable?"block":"none";
c.btn.style.position="absolute";c.btn.style.left=d.pickerFace+"px";c.btn.style.bottom=d.pickerFace+"px";c.btn.style.padding="0 15px";c.btn.style.height="18px";c.btn.style.border=d.pickerInset+"px solid";(function(){var a=d.pickerInsetColor.split(/\s+/);c.btn.style.borderColor=2>a.length?a[0]:a[1]+" "+a[0]+" "+a[0]+" "+a[1]})();c.btn.style.color=d.pickerButtonColor;c.btn.style.font="12px sans-serif";c.btn.style.textAlign="center";try{c.btn.style.cursor="pointer"}catch(D){c.btn.style.cursor="hand"}c.btn.onmousedown=
function(){d.hidePicker()};c.btnS.style.lineHeight=c.btn.style.height;switch(l){case 0:var f="hs.png";break;case 1:f="hv.png"}c.padM.style.backgroundImage="url('"+jscolor.getDir()+"cross.gif')";c.padM.style.backgroundRepeat="no-repeat";c.sldM.style.backgroundImage="url('"+jscolor.getDir()+"arrow.gif')";c.sldM.style.backgroundRepeat="no-repeat";c.pad.style.backgroundImage="url('"+jscolor.getDir()+f+"')";c.pad.style.backgroundRepeat="no-repeat";c.pad.style.backgroundPosition="0 0";B();C();jscolor.picker.owner=
d;document.getElementsByTagName("body")[0].appendChild(c.boxB)}function y(a){return[2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[0]+(a.slider?2*a.pickerInset+2*jscolor.images.arrow[0]+jscolor.images.sld[0]:0),a.pickerClosable?4*a.pickerInset+3*a.pickerFace+jscolor.images.pad[1]+a.pickerButtonHeight:2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[1]]}function B(){switch(l){case 0:var b=1;break;case 1:b=2}jscolor.picker.padM.style.backgroundPosition=d.pickerFace+d.pickerInset+Math.round(d.hsv[0]/
6*(jscolor.images.pad[0]-1))-Math.floor(jscolor.images.cross[0]/2)+"px "+(d.pickerFace+d.pickerInset+Math.round((1-d.hsv[b])*(jscolor.images.pad[1]-1))-Math.floor(jscolor.images.cross[1]/2))+"px";b=jscolor.picker.sld.childNodes;switch(l){case 0:for(var k=a(d.hsv[0],d.hsv[1],1),e=0;e<b.length;e+=1)b[e].style.backgroundColor="rgb("+k[0]*(1-e/b.length)*100+"%,"+k[1]*(1-e/b.length)*100+"%,"+k[2]*(1-e/b.length)*100+"%)";break;case 1:var f=[d.hsv[2],0,0];e=Math.floor(d.hsv[0]);var c=e%2?d.hsv[0]-e:1-(d.hsv[0]-
e);switch(e){case 6:case 0:k=[0,1,2];break;case 1:k=[1,0,2];break;case 2:k=[2,0,1];break;case 3:k=[2,1,0];break;case 4:k=[1,2,0];break;case 5:k=[0,2,1]}for(e=0;e<b.length;e+=1){var h=1-1/(b.length-1)*e;f[1]=f[0]*(1-h*c);f[2]=f[0]*(1-h);b[e].style.backgroundColor="rgb("+100*f[k[0]]+"%,"+100*f[k[1]]+"%,"+100*f[k[2]]+"%)"}}}function C(){switch(l){case 0:var a=2;break;case 1:a=1}jscolor.picker.sldM.style.backgroundPosition="0 "+(d.pickerFace+d.pickerInset+Math.round((1-d.hsv[a])*(jscolor.images.sld[1]-
1))-Math.floor(jscolor.images.arrow[1]/2))+"px"}function t(){return jscolor.picker&&jscolor.picker.owner===d}function E(){h!==b&&d.importColor()}function z(a){var b=jscolor.getRelMousePos(a);a=b.x-d.pickerFace-d.pickerInset;b=b.y-d.pickerFace-d.pickerInset;switch(l){case 0:d.fromHSV(6/(jscolor.images.pad[0]-1)*a,1-b/(jscolor.images.pad[1]-1),null,u);break;case 1:d.fromHSV(6/(jscolor.images.pad[0]-1)*a,null,1-b/(jscolor.images.pad[1]-1),u)}}function A(a){a=jscolor.getRelMousePos(a).y-d.pickerFace-
d.pickerInset;switch(l){case 0:d.fromHSV(null,null,1-a/(jscolor.images.sld[1]-1),v);break;case 1:d.fromHSV(null,1-a/(jscolor.images.sld[1]-1),null,v)}}function r(){if(d.onImmediateChange)if("string"===typeof d.onImmediateChange)eval(d.onImmediateChange);else d.onImmediateChange(d)}this.adjust=this.required=!0;this.hash=!1;this.slider=this.caps=!0;this.styleElement=this.valueElement=b;this.onImmediateChange=null;this.hsv=[0,0,1];this.rgb=[1,1,1];this.pickerOnfocus=!0;this.pickerMode="HSV";this.pickerPosition=
"bottom";this.pickerSmartPosition=!0;this.pickerButtonHeight=20;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=0;this.pickerFaceColor="ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDHighlight ThreeDHighlight ThreeDShadow";this.pickerZIndex=1E4;for(var w in e)e.hasOwnProperty(w)&&(this[w]=e[w]);this.hidePicker=function(){t()&&
(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(){t()||(jscolor.getElementPos(b),jscolor.getElementSize(b),jscolor.getViewPos(),jscolor.getViewSize(),y(this),this.pickerPosition.toLowerCase(),m(0,0))};this.importColor=function(){h?this.adjust?!this.required&&/^\s*$/.test(h.value)?(h.value="",f.style.backgroundImage=f.jscStyle.backgroundImage,f.style.backgroundColor=f.jscStyle.backgroundColor,f.style.color=f.jscStyle.color,
this.exportColor(q|x)):this.fromString(h.value)||this.exportColor():this.fromString(h.value,q)||(f.style.backgroundImage=f.jscStyle.backgroundImage,f.style.backgroundColor=f.jscStyle.backgroundColor,f.style.color=f.jscStyle.color,this.exportColor(q|x)):this.exportColor()};this.exportColor=function(a){if(!(a&q)&&h){var b=this.toString();this.caps&&(b=b.toUpperCase());this.hash&&(b="#"+b);h.value=b}a&x||!f||(f.style.backgroundImage="none",f.style.backgroundColor="#"+this.toString(),f.style.color=.5>
.213*this.rgb[0]+.715*this.rgb[1]+.072*this.rgb[2]?"#FFF":"#000");a&v||!t()||B();a&u||!t()||C()};this.fromHSV=function(b,d,e,f){0>b&&(b=0);6<b&&(b=6);0>d&&(d=0);1<d&&(d=1);0>e&&(e=0);1<e&&(e=1);this.rgb=a(null===b?this.hsv[0]:this.hsv[0]=b,null===d?this.hsv[1]:this.hsv[1]=d,null===e?this.hsv[2]:this.hsv[2]=e);this.exportColor(f)};this.fromRGB=function(a,b,d,e){0>a&&(a=0);1<a&&(a=1);0>b&&(b=0);1<b&&(b=1);0>d&&(d=0);1<d&&(d=1);a=null===a?this.rgb[0]:this.rgb[0]=a;b=null===b?this.rgb[1]:this.rgb[1]=
b;var c=null===d?this.rgb[2]:this.rgb[2]=d,f=Math.min(Math.min(a,b),c);d=Math.max(Math.max(a,b),c);var g=d-f;0===g?a=[null,0,d]:(a=a===f?3+(c-b)/g:b===f?5+(a-c)/g:1+(b-a)/g,a=[6===a?0:a,g/d,d]);null!==a[0]&&(this.hsv[0]=a[0]);0!==a[2]&&(this.hsv[1]=a[1]);this.hsv[2]=a[2];this.exportColor(e)};this.fromString=function(a,b){return(a=a.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i))?(6===a[1].length?this.fromRGB(parseInt(a[1].substr(0,2),16)/255,parseInt(a[1].substr(2,2),16)/255,parseInt(a[1].substr(4,
2),16)/255,b):this.fromRGB(parseInt(a[1].charAt(0)+a[1].charAt(0),16)/255,parseInt(a[1].charAt(1)+a[1].charAt(1),16)/255,parseInt(a[1].charAt(2)+a[1].charAt(2),16)/255,b),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};var d=this,l="hvs"===this.pickerMode.toLowerCase()?1:0,h=jscolor.fetchElement(this.valueElement),f=jscolor.fetchElement(this.styleElement),
n=!1,p=!1,q=1,x=2,v=4,u=8;h&&(e=function(){d.fromString(h.value,q);r()},jscolor.addEvent(h,"keyup",e),jscolor.addEvent(h,"input",e),jscolor.addEvent(h,"blur",E),h.setAttribute("autocomplete","off"));f&&(f.jscStyle={backgroundImage:f.style.backgroundImage,backgroundColor:f.style.backgroundColor,color:f.style.color});switch(l){case 0:jscolor.requireImage("./images/hs.png");break;case 1:jscolor.requireImage("./images/hv.png")}jscolor.requireImage("./images/cross.gif");jscolor.requireImage("./images/arrow.gif");
this.importColor()}};jscolor.install();